name: Deploy JupiterLyte Page

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.WEBSITE_PK }}

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Checkout xDSL
      run: |
        XDSL_COMMIT=$(grep xdsl requirements.txt|grep -o -P '(?<=@).*(?=#)')
        git clone https://github.com/xdslproject/xdsl.git
        cd xdsl
        git checkout $XDSL_COMMIT

    - name: Install dependencies
      run: |
        python -m pip install jupyterlite[all] libarchive-c build pyodide-build

    - name: Build xDSL source distribution
      run: |
        cd xdsl
        python setup.py sdist

    # Pyodide is cached, so cloned only if not present in the cache, otherwise
    # just checked out to whatever desired version and partially rebuilt.

    - name: Restore cached Pyodide tree
      id: cache-pyodide
      uses: actions/cache/restore@v3
      with:
        path: pyodide
        key: pyodide

    - name: Clone pyodide if not cached
      if: steps.cache-pyodide.outputs.cache-hit != 'true'
      run: git clone https://github.com/pyodide/pyodide.git

    # Clean the xDSL and FrozenList package folders, generate their skeletons
    # and do the necessary updates before building.
    - name: Build custom Pyodide distribution
      run: |
        
        cd pyodide
        git fetch --all
        git checkout 0.22.0a3
        python -m pip install -r requirements.txt
        sudo apt update && sudo apt install f2c
        
        rm packages/xdsl packages/frozenlist -rf
        pyodide skeleton pypi xdsl
        pyodide skeleton pypi frozenlist
        
        ../.github/workflows/update_xdsl_pyodide_build.py packages/xdsl/meta.yaml ../xdsl
        
        PYODIDE_PACKAGES="frozenlist,coverage,xdsl" make

    - name: Cache Pyodide tree
      uses: actions/cache/save@v3
      with:
        path: pyodide
        key: pyodide

    - name: Build the JupyterLite site
      run: |
        mkdir content
        cp xdsl/docs/* content -r
        
        rm -rf pyodide/pyodide
        mkdir pyodide/pyodide
        mv pyodide/dist pyodide/pyodide/pyodide
        
        python -m jupyter lite build --contents content --pyodide pyodide/pyodide

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_output

    - name: Deploy private website
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        ssh-keyscan -H xdsl-workshop.datenvorr.at >> ~/.ssh/known_hosts
        rsync -r --delete _output/* website@xdsl-workshop.datenvorr.at:/home/website/public

